- name: Hello World Sample
  hosts: all
  tasks:
    - name: Setting Facts
      set_fact:
        my_yaml: "{{ my_yaml_string | from_yaml }}"
    - name: Print items
      debug:
        msg: "{{ item }}"
      with_items: "{{ my_yaml }}"
    - name: Print names
      debug:
        msg: "{{ item.name }}"
      with_items: "{{ my_yaml }}"
    - name: Print ips
      debug:
        msg: "{{ item.ip }}"
      with_items: "{{ my_yaml }}"
    - name: Print ports
      debug:
        msg: "{{ item.port }}"
      with_items: "{{ my_yaml }}"
